// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxn0KnEfAB3bNofb6dvuYNJsKlcDJvi0g',
    appId: '1:858505248896:web:c38c08eaac80f986466665',
    messagingSenderId: '858505248896',
    projectId: 'cw07-f3d73',
    authDomain: 'cw07-f3d73.firebaseapp.com',
    storageBucket: 'cw07-f3d73.appspot.com',
    measurementId: 'G-TR1JYSYE5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEi9Rp3KsaezE0J2nq0onSGbO6tMxxJAA',
    appId: '1:858505248896:android:0d638449588c3946466665',
    messagingSenderId: '858505248896',
    projectId: 'cw07-f3d73',
    storageBucket: 'cw07-f3d73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrz4DcjjGhTO4zZZ86mIOMow0eVeizCtk',
    appId: '1:858505248896:ios:b4ae8033b3a36113466665',
    messagingSenderId: '858505248896',
    projectId: 'cw07-f3d73',
    storageBucket: 'cw07-f3d73.appspot.com',
    iosClientId: '858505248896-lc0qp34gcc2eigaujg8fcnqhq8vid166.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );

}